name: Lint
on: pull_request
jobs:
  lint-metainfo:
    name: Lint metainfo file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - run: sudo apt install -y appstream-util
    - run: appstream-util validate --nonet io.github.Cockatrice.appdata.xml
