name: Lint
on: pull_request
jobs:
  validate-appdata:
    name: Validate AppData
    runs-on: ubuntu-latest
    container: ubuntu:mantic   # see #49, can be changed to ubuntu:rolling later
    steps:
    - uses: actions/checkout@v4
    - run: apt-get update
    - run: apt-get -y install appstream
    - name: Print versions
      run: |
        cat /etc/os-release | egrep "PRETTY_NAME|VERSION_ID"
        echo ""
        appstreamcli --version
    - run: appstreamcli validate --pedantic io.github.Cockatrice.appdata.xml
